### ISSUE TITLE
socieboy forum

### ISSUE THREAD

**Issue by wilzxl** [stygiansabyss/LaravelBase#1]
Hello Travis, 

I found you ever worked on the **society forum** on github, and I'm now learning Laravel through building the forum, but I met a problem that I couldn't get into the forum page even though I had set all parameters. 

When I got into localhost, the "Laravel 5" main page was the only thing I could see. Could you please help me with the problem? Do I need to set parameters in app/Http/route.php or just copy the route.php in socieboy forum folder into Laravel package? Thank you for your time!

Best,
William

**Comment by stygiansabyss** [comment]
It would be best to pose that question on laracasts.com.  The problem you are having is a very key concept to laravel which is understanding how routes lead to controller which render views.
